_target_: tt_boltz.boltzgen.task.predict.predict.Predict
data:
  _target_: tt_boltz.boltzgen.task.predict.data_from_yaml.FromYamlDataModule
  cfg:
    _target_: tt_boltz.boltzgen.task.predict.data_from_yaml.DataConfig
    tokenizer:
      _target_: tt_boltz.boltzgen.data.tokenizer.Tokenizer
      atomize_modified_residues: false
    featurizer:
      _target_: tt_boltz.boltzgen.data.featurizer.Featurizer
    moldir: /home/ttuser/.boltz/boltzgen/mols.zip
    yaml_path:
    - examples/binder.yaml
    output_dir: ${output}
    diffusion_samples: ${diffusion_samples}
    backbone_only: false
    atom14: true
    atom37: false
    disulfide_prob: 1.0
    disulfide_on: true
    skip_existing: false
    multiplicity: 1
  batch_size: 1
  num_workers: 1
writer:
  _target_: tt_boltz.boltzgen.task.predict.writer.DesignWriter
  output_dir: ${output}
  res_atoms_only: false
  atom14: ${data.cfg.atom14}
  atom37: ${data.cfg.atom37}
  backbone_only: ${data.cfg.backbone_only}
  write_native: false
trainer:
  devices: 1
name: null
output: binder/shards/device_2/intermediate_designs
checkpoint: /home/ttuser/.boltz/boltzgen/boltzgen1_diverse.ckpt
recycling_steps: 3
sampling_steps: 500
diffusion_samples: 1
override:
  masker_args:
    mask: true
    mask_backbone: false
  validators: null
  step_scale_schedule:
  - step_scale: 1.8
    period: 0.25
  - step_scale: 2.0
    period: 0.25
  - step_scale: 1.8
    period: 0.25
  - step_scale: 2.0
    period: 0.25
  noise_scale_schedule:
  - noise_scale: 0.95
    period: 0.25
  - noise_scale: 0.88
    period: 0.25
  - noise_scale: 0.95
    period: 0.25
  - noise_scale: 0.88
    period: 0.25
  diffusion_process_args:
    sigma_min: 0.0004
    sigma_max: 160.0
    sigma_data: 16.0
    rho: 7
    P_mean: -1.2
    P_std: 1.5
    gamma_0: 0.8
    gamma_min: 1.0
    noise_scale: null
    step_scale: null
    mse_rotational_alignment: true
    coordinate_augmentation: true
    alignment_reverse_diff: true
    synchronize_sigmas: false
    sampling_schedule: dilated
    time_dilation: 2.667
    time_dilation_start: 0.6
    time_dilation_end: 0.8
  use_kernels: false
  checkpoints:
    first_checkpoint_num_samples: 0.5
    checkpoint_list:
    - checkpoint:
        num_samples: 0.5
        path: /home/ttuser/.boltz/boltzgen/boltzgen1_adherence.ckpt
